version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./infrastructure/docker/go/Dockerfile
  #   networks:
  #     - mynet
  #   ports:
  #     - 80:8080
  #   environment:
  #     DB_CONNECTION: mysql
  #     DB_HOST: db
  #     DB_PORT: 3306
  #     DB_DATABASE: xboard
  #     DB_USERNAME: admin
  #     DB_PASSWORD: secret

  docker-gs-ping-roach:
    depends_on:
      - roach
    build:
      context: .
      dockerfile: ./infrastructure/docker/go/Dockerfile
    volumes:
      - ./backend:/app
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE-mydb}

  roach:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: roach
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach:

networks:
  mynet:
    driver: bridge

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./infrastructure/docker/mysql/Dockerfile
  #   networks:
  #     - mynet
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db-store:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: go_example
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
